name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: Run go vet
        run: go vet ./...

      - name: Run unit tests
        run: go test ./... -timeout=60s
